# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - QuranicSearch

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://quran.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_2bc74d16a6f845118d4d3e5369aafd14 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_3760f4e669d64ebc9b4351277d084f7b }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: quran.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_2bc74d16a6f845118d4d3e5369aafd14 }}/quran-app:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'QuranicSearch'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_ae3af661dc004e319a92f1d02e97ea46 }}
        images: 'quran.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_2bc74d16a6f845118d4d3e5369aafd14 }}/quran-app:${{ github.sha }}'